name:                Youtube-Recommended-Crawl
version:             0.1.0.0
github:              "ILikePizza555/Youtube-Recommended-Crawl"
license:             BSD3
author:              "Isaac &quot;Izzy&quot; Avram"
maintainer:          "avrisaac555@gmail.com"
copyright:           "2018 Isaac &quot;Izzy&quot; Avram"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ILikePizza555/Youtube-Recommended-Crawl#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- bytestring
- http-client
- http-conduit
- exceptions >= 0.10.0
- split == 0.2.3.3
- text
- time
- unordered-containers

library:
  source-dirs: src

executables:
  Youtube-Recommended-Crawl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Youtube-Recommended-Crawl

tests:
  Youtube-Recommended-Crawl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Youtube-Recommended-Crawl
